--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrEcstsy/AdvancedEnchantments
build-by-default: true
branches:
- main
projects:
  AdvancedEnchantments:
    path: ""
    libs: 
      - src: "muqsit/InvMenu/InvMenu"
        branch: pm5
        version: 4.6.5
      - src: "Paroxity/Commando/Commando"
        version: "^3.2.0"
      - src: "muqsit/simplepackethandler/SimplePacketHandler"
        branch: pm5
        version: "^0.1.4"
...
