name: AdvancedEnchantments
main: ecstsy\AdvancedEnchantments\Loader
api: 5.3.0
version: 1.0.0
authors:
  - ecstsy

permissions:
  advancedenchantments.default:
    default: op
    description: "Default permission for AdvancedEnchantments"
  advancedenchantments.enchant:
    default: op
  advancedenchantments.giveitem:
    default: op
    