name: AdvancedEnchantments
main: ecstsy\AdvancedEnchantments\Loader
api: 5.3.0
version: 1.0.1-BETA
authors:
  - ecstsy

permissions:
  advancedenchantments.default:
    default: op
    description: "Default permission for AdvancedEnchantments"
  advancedenchantments.enchant:
    default: op
  advancedenchantments.giveitem:
    default: op
  advancedenchantments.unenchant:
    default: op 
  advancedenchantments.list: 
    default: true 
  advancedenchantments.give:
    default: op
  advancedenchantments.info:
    default: true
  advancedenchantments.reload:
    default: op   
  advancedenchantments.give-rcbook:
    default: op
  advancedenchantments.enchanter:
    default: true
    
