# AdvancedEnchantments
# Recoded by ecstsy
Version: 1.0.0
# 
# ** Commands and permissions
# /enchanter - Open Enchanter; no permission
# /tinkerer - Open Tinkerer; no permission
# /gkits - Open GKits; no permission
# /ae - Main plugin command; ae.help
# /ae about - Information about current build; no permission
# /ae list - List all custom enchantments; ae.list
# /ae admin - Open a menu with all possible enchantments (100% success rate); ae.admin
# /ae giveitem <player> <item> - Give various plugin items; ae.giveitem
# /ae give <player> <enchantment> <level> - Give custom enchanted book; ae.give
# /ae info <enchantment> - Information about custom enchantment; ae.info
# /ae reload - Reload all configurations; ae.reload
# /ae enchant <enchantment> <level> - Enchant item; ae.enchant
# /ae givebook <player> <enchantment> <level> <count> <success> <destroy> - Give book with specific rates; ae.givebook
# /ae givercbook <type> <player> <amount> - Give right-clickable book; ae.givercbook
# /ae giverandombook <player> <group> - Gives random book from group; ae.giverandombook
# /ae pasteenchants - Pastes formatted enchantments list; ae.admin
# /alchemist - Open alchemist; no permission
# /ae givegkit <player> <gkit> - Give player gkit items; ae.givegkit
# 
# /aegive - Give player gkit items; ae.give
# Example: /aegive GC diamond_helmet 1 name:&&7cItem_name protection:5 glowing:1 lore:&&7cLore_line_#1|&&7cSecond_Line
# 
# /asets - Advanced Sets commands; asets.admin
# 
# Some configurable settings are explained, others should be self-explanatory.
# Join support discord for help or with questions: https://advancedplugins.net/discord
# 
# Change default messages language. You can modify all messages in AdvancedEnchantments `locale` folder.
# See all default languages & other info here: https://ae.advancedplugins.net/general-information/languages
economy:
  provider: essentialsx

language: en-us

commands:
  enchanter:
    enabled: true
    command: /enchanter
    aliases:
    - e
    - ce
  tinkerer:
    enabled: true
    command: /tinkerer
    aliases:
    - tinker
  alchemist:
    enabled: true
    command: /alchemist
    aliases:
    - alchem
  withdrawsouls:
    enabled: true
    command: /withdrawsouls
    aliases:
    - wsouls
  apply: # Reapplies current worn armor's effects, repeating effects as well
    enabled: true
    command: /apply
    aliases:
    - reapply

disable-enchants:
  # Disable enchants in specific world
  test_world: # world name
    - test_enchant

# Only disables armorsets events
disable-armorsets:
  # Disable armorsets in specific world
  test_world: # world name
    - test_armorset

souls:
  enabled: true
  lore: '&cSouls Collected: %souls%'
  item:
    type: PAPER
    name: '&f&lSoul Tracker'
    lore:
      - '&7Apply to weapons to start tracking'
      - '&7souls collected from kills.'

# Enchantments limitation
# If an item contains the specified lore, or the specified NBT tag, custom enchants
# will not be able to be applied.
enchantLimitation:
  enabled: true
  lore: '&r&c&lUnmodifiable'
  NBT-tag: unmodifiable

# Enchantment combining (leveling up) on items.
# Example: https://media.giphy.com/media/26n6QDunj6iC3Z6Zq/giphy.gif
combining:
  enabled: true
  chances:
    # If true, Success and Destroy chances will effect combining
    use-chances: true
    # If true, item will break (if Protection is added, protection will be removed).
    break-item: false
    # If higher level of enchantment already on item is applied, should the enchantment upgrade?
    upgrade: true

# Limit number of enchantments item can have
slots:
  enabled: true
  # Max number of enchantments
  max: 9
  # Max slots increasement with slot increase
  # This is a total slot number that can be with upgrades
  max-increase-of-slots: 13
  # Should it be displayed in lore?
  display-in-lore: false
  display: '&eItem Slots&7: {left}'

# Applying enchantment book section
# Miscellaneous settings for applying
# enchantment books to items (dragging book to item).
applying:
  cosmetics:
    applied:
      particle: "minecraft:villager_happy"
      sound: random.levelup
    failed:
      particle: LAVA_POP
      sound: random.anvil_berak

enchanter-books:
  firework-on-open: true
  cosmetics:
    particle: "minecraft:villager_happy"
    sound: random.levelup
  display-right-click-message: true
  # Variables: {enchant} - enchantment name
  # {enchant-color} - enchantment name with color
  # {level} - level number in roman
  message:
    - '&r&7You examined {group-color}{group-name}&r&7 book and found {enchant-color} {level}'
  type: 'book'
  force-glow: false
  name: '&r{group-color}{group-name}&l Enchantment Book &r&7(Right Click)'
  lore:
    - '&r&7Right Click while holding to receive a random'
    - '&r{group-color}{group-name} &r&7enchantment book.'

items:
  settings:
    can-apply-to:
      - ALL_SWORD
      - ALL_ARMOR
      - ALL_PICKAXE
      - ALL_AXE
      - ALL_SPADE
      - ALL_HOE
      - ALL_EDIBLE
      - BOOK
      - BOW
      - CROSSBOW
      - ELYTRA
      - TRIDENT
  transmogscroll:
    type: 'paper'
    name: '&r&c&lTransmog Scroll'
    lore:
      - '&r&7Organizes enchants by &erarity&7 on item'
      - '&r&7and adds the &dlore &bcount&7 to name.'
      - ''
      - '&r&e&oPlace scroll on item to apply.'
    enchants-count-formatting: '&d[&b{count}&d]'
  soulgem:
    type: 'emerald'
    name: '&c&lSoul Gem &7[&a{count}&7]'
    lore:
      - '&7Apply to an item to add souls.'
  itemnametag:
    type: 'name_tag'
    name: '&6&lItem NameTag &7(Right Click)'
    lore:
      - '&7Rename and customize your equipment'
    messages:
      success:
        - '&a&l(!) &aYou have successfully renamed your item to &e%name%'
      activated:
        - '&a&l(!) &aYour next message will rename your item in hand'
      air:
        - '&c&l(!) &cYou need to be holding an item to do this'
      renaming-not-enchanted-item:
        - '&c&l(!) &cYou can only rename enchanted items'
    settings:
      colors: true
      word-blacklist:
      - fuck
      - dick
      - bitch
  randomization-scroll:
    type: 'paper'
    name: '{group-color}{group-name}&l{group-color} Randomization Scroll'
    lore:
    - ''
    - '&7Apply to any {group-color}{group-name} &7Enchantment Book'
    - '&7to reroll the success and destroy rates.'
    - ''
    - '&7Drag n'' drop onto enchantment book&7 to apply.'
  black-scroll:
    type: 'ink_sac'
    name: '&f&lBlack Scroll'
    lore:
    - '&7Removes a random enchantment'
    - '&7from an item and converts'
    - '&7it into a &f{success}% &7success book.'
    - '&fPlace scroll onto item to extract.'
    success: 95
    destroy: 5
    random: true
  secret-dust:
    type: 'fire_charge'
    name: '{group-color}{group-name}{group-color} Secret Dust &7(Right Click)'
    lore:
    - '&7Contains: &bMagic, &fMystery &7dust.'
    - '&7An unidentified satchel of dust.'
  mystery-dust:
    type: 'gunpoweder'
    name: '&fMystery Dust'
    lore:
    - '&7A failed bi-product'
    - '&7of Magic dust.'
  magic-dust:
    type: 'sugar'
    name: '{group-color}{group-name}{group-color} Magic Dust'
    lore:
    - '&a+{percent}% Success'
    - '&7Apply to a &7any {group-color}{group-name} &7Enchantment Book'
    - '&7to increase its success by {group-color}{percent}%'
    messages:
      cannotApplyToStacked: '&c&l(!) &cCannot be applied to stacked books'
  slot-increaser:
    type: 'ender_eye'
    name: '{group-color}&l{group-name} Slot Increaser'
    lore:
    - '&7Increase slots limit on an item by &a+{count}'
    messages:
      success:
      - '&a&l(!) &aYou have successfully increased maximum slots on item by {count}!'
  blocktrak:
    type: 'slime_ball'
    name: '&aBlockTrak Creator'
    lore:
      - '&7Track how many blocks you break with a tool'
      - '&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &aBlockTrak Creator'
    settings:
      lore-display: '&r&eBlockTrak Blocks Broken: &6{stats}'
  stattrak:
    type: 'magma_cream'
    name: '&r&eStatTrak Creator'
    lore:
      - '&r&7Track how many kills you have with a weapon'
      - '&r&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &eStatTrak Creator'
    settings:
      lore-display: '&eStatTrak Kills: &6{stats}'
  mobtrak:
    type: "slime_ball"
    name: '&r&3MobTrak Creator'
    lore:
      - '&r&7track how many mob kills you have with a weapon'
      - '&r&7Drag ontop of another item to apply it'
    messages:
      success:
        - '&7You successfully applied &3MobTrak Creator'
    settings:
      lore-display: '&r&3MobTrak Kills: &f{stats}'
  holywhitescroll:
    type: 'paper'
    name: '&r&6&lHoly White Scroll'
    lore:
      - '&r&eA legendary reward that can'
      - '&r&ebe applied to armor/weapons,'
      - '&r&egives a 100% chance of not losing'
      - '&r&ethe blessed item on death.'
    messages:
      applied:
        - '&7You successfully applied &6&lHoly White Scroll'
    settings:
      lore-display: '&r&e&l*&f&lHOLY&e&l* &f&lPROTECTED'
      keep-after-death: false
  orb:
    lore: '&r&a{max} Enchantment Slots &7(Orb [&a+{increased}&7])'
    weapon:
      material: "ender_eye"
      name: '&r&6&lWeapon Enchantment Orb &6[&a{max}&6]'
      lore:
        - '&r&a{success}% Success Rate'
        - ''
        - '&r&6+{new} Enchantment slots'
        - '&r&6{max} Max Enchantment Slots'
        - ''
        - '&r&eIncreases the # of enchantment'
        - '&r&eslots on a weapon by {new},'
        - '&r&eup to a maximum of {max}'
        - '&r&7Drag n'' Drop onto an item to apply.'
    armor:
      material: "ender_eye"
      name: '&r&6&lArmor Enchantment Orb &6[&r&a{max}&l&6]'
      lore:
        - '&r&a{success}% Success Rate'
        - ''
        - '&r&6+{new} Enchantment slots'
        - '&r&6{max} Max Enchantment Slots'
        - ''
        - '&r&eIncreases the # of enchantment'
        - '&r&eslots on a piece of armor by {new},'
        - '&r&eup to a maximum of {max}'
        - '&r&7Drag n'' Drop onto an item to apply.'
    tool:
      material: "ender_eye"
      name: '&r&6&lTool Enchantment Orb &6[&a{max}&6]'
      lore:
        - '&r&a%success%% Success Rate'
        - ''
        - '&r&6+%new% Enchantment slots'
        - '&r&6{max} Max Enchantment Slots'
        - ''
        - '&r&eIncreases the # of enchantment'
        - '&r&eslots on a tool by %new%,'
        - '&r&eup to a maximum of {max}'
        - '&r&7Drag n'' Drop onto an item to apply.'
  white-scroll:
    delete: true
    lore-display: '&r&f&lPROTECTED'
    type: 'empty_map'
    force-glow: false
    name: "&r&fWhite Scroll"
    lore:
      - '&r&fPrevents an item from being destroyed'
      - '&r&fdue to a failed Enchantment Book.'
      - '&r&ePlace scroll on item to apply.'

destroy:
  # Should book be destroyed if it fails?
  enabled: true
  # Should Item be destroyed?
  destroy-item: false

chances:
  # Should book chances be random?
  random: true
  # If not random, what should be the simple values?
  # Can use `<min-max>` to define range between
  success: 92
  destroy: 8
  # If applying book fails, should the plugin destroy item 100% of the time or use Destroy from book to give a chance to
  # neither apply to enchant neither destroy. If set to "enabled: true', item will always be destroyed.
  destroy-if-fail:
    enabled: false

enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: false
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: 'enchanted_book'
    force-glow: false
  # Variables: {enchant}, {enchant-no-color}, {description}, {level-description}, {applies}, {success}, {destroy}, {color}, {max-level}
  name: '&r{group-color}&l{enchant-no-color} {level}'
  lore:
    - '&r&a{success}% Success Rate'
    - '&r&c{destroy}% Destroy Rate'
    - '&r&e{description}'
    - '&r&7{applies-to} Enchantment'
    - "&r&7Drag n' drop onto item to enchant"