# AdvancedEnchantments
# Recoded by ecstsy
Version: 1.0.0
# 
# ** Commands and permissions
# /enchanter - Open Enchanter; no permission
# /tinkerer - Open Tinkerer; no permission
# /gkits - Open GKits; no permission
# /ae - Main plugin command; ae.help
# /ae about - Information about current build; no permission
# /ae list - List all custom enchantments; ae.list
# /ae admin - Open a menu with all possible enchantments (100% success rate); ae.admin
# /ae giveitem <player> <item> - Give various plugin items; ae.giveitem
# /ae give <player> <enchantment> <level> - Give custom enchanted book; ae.give
# /ae info <enchantment> - Information about custom enchantment; ae.info
# /ae reload - Reload all configurations; ae.reload
# /ae enchant <enchantment> <level> - Enchant item; ae.enchant
# /ae givebook <player> <enchantment> <level> <count> <success> <destroy> - Give book with specific rates; ae.givebook
# /ae givercbook <type> <player> <amount> - Give right-clickable book; ae.givercbook
# /ae giverandombook <player> <group> - Gives random book from group; ae.giverandombook
# /ae pasteenchants - Pastes formatted enchantments list; ae.admin
# /alchemist - Open alchemist; no permission
# /ae givegkit <player> <gkit> - Give player gkit items; ae.givegkit
# 
# /aegive - Give player gkit items; ae.give
# Example: /aegive GC diamond_helmet 1 name:&&7cItem_name protection:5 glowing:1 lore:&&7cLore_line_#1|&&7cSecond_Line
# 
# /asets - Advanced Sets commands; asets.admin
# 
# Some configurable settings are explained, others should be self-explanatory.
# Join support discord for help or with questions: https://advancedplugins.net/discord
# 
# Change default messages language. You can modify all messages in AdvancedEnchantments `locale` folder.
# See all default languages & other info here: https://ae.advancedplugins.net/general-information/languages
language: en-us
commands:
  enchanter:
    enabled: true
    command: /enchanter
    aliases:
    - e
    - ce
    permission: ae.enchanter
  tinkerer:
    enabled: true
    command: /tinkerer
    aliases:
    - tinker
    permission: ae.tinkerer
  alchemist:
    enabled: true
    command: /alchemist
    aliases:
    - alchem
    permission: ae.alchemist
  withdrawsouls:
    enabled: true
    command: /withdrawsouls
    aliases:
    - wsouls
    permission: ae.withdrawsouls
  apply:
    enabled: true
    command: /apply
    aliases:
    - reapply
    permission: ae.apply
disable-enchants:
  test_world:
  - test_enchant
applying:
  cosmetics:
    applied:
      particle: HAPPY_VILLAGER
      sound: LEVEL_UP
    failed:
      particle: LAVA_POP
      sound: ANVIL_BREAK
enchanter-books:
  firework-on-open: true
  cosmetics:
    particle: HAPPY_VILLAGER
    sound: LEVEL_UP
  display-right-click-message: true
  type: BOOK
  id: 0
  custom-model-data: 0
  force-glow: false
  name: '{group-color}{group-name}&l Enchantment Book &r&7(Right Click)'
  lore:
  - '&r&7Right Click while holding to receive a random'
  - '{group-color}{group-name} &r&7enchantment book.'
items:
  settings:
    can-apply-to:
    - ALL_SWORD
    - ALL_ARMOR
    - ALL_PICKAXE
    - ALL_AXE
    - ALL_SPADE
    - ALL_HOE
    - ALL_EDIBLE
    - BOOK
    - BOW
    - CROSSBOW
    - ELYTRA
    - TRIDENT
  transmogscroll:
    type: 'paper'
    name: '&r&c&lTransmog Scroll'
    lore:
    - '&r&7Organizes enchants by &erarity&7 on item'
    - '&r&7and adds the &dlore &bcount&7 to name.'
    - ''
    - '&r&e&oPlace scroll on item to apply.'
    enchants-count-formatting: '&d[&b{count}&d]'
  soulgem:
    type: 'emerald'
    name: '&c&lSoul Gem &7[&a{count}&7]'
    lore:
    - '&7Apply to an item to add souls.'
  itemnametag:
    type: 'name_tag'
    name: '&6&lItem NameTag &7(Right Click)'
    lore:
    - '&7Rename and customize your equipment'
    messages:
      success:
      - '&a&l(!) &aYou have successfully renamed your item to &e%name%'
      activated:
      - '&a&l(!) &aYour next message will rename your item in hand'
      air:
      - '&c&l(!) &cYou need to be holding an item to do this'
      renaming-not-enchanted-item:
      - '&c&l(!) &cYou can only rename enchanted items'
    settings:
      colors: true
      word-blacklist:
      - fuck
      - dick
      - bitch
  randomization-scroll:
    type: 'paper'
    name: '{group-color}{group-name}&l{group-color} Randomization Scroll'
    lore:
    - ''
    - '&7Apply to any {group-color}{group-name} &7Enchantment Book'
    - '&7to reroll the success and destroy rates.'
    - ''
    - '&7Drag n'' drop onto enchantment book&7 to apply.'
  black-scroll:
    type: 'ink_sac'
    name: '&f&lBlack Scroll'
    lore:
    - '&7Removes a random enchantment'
    - '&7from an item and converts'
    - '&7it into a &f{success}% &7success book.'
    - '&fPlace scroll onto item to extract.'
    success: 95
    destroy: 5
    random: true
  secret-dust:
    type: 'fireball'
    name: '{group-color}{group-name}{group-color} Secret Dust &7(Right Click)'
    lore:
    - '&7Contains: &bMagic, &fMystery &7dust.'
    - '&7An unidentified satchel of dust.'
  mystery-dust:
    type: 'sulphur'
    name: '&fMystery Dust'
    lore:
    - '&7A failed bi-product'
    - '&7of Magic dust.'
  magic-dust:
    type: 'sugar'
    name: '{group-color}{group-name}{group-color} Magic Dust'
    lore:
    - '&a+{percent}% Success'
    - '&7Apply to a &7any {group-color}{group-name} &7Enchantment Book'
    - '&7to increase its success by {group-color}{percent}%'
    messages:
      cannotApplyToStacked: '&c&l(!) &cCannot be applied to stacked books'
  slot-increaser:
    type: 'ender_eye'
    name: '{group-color}&l{group-name} Slot Increaser'
    lore:
    - '&7Increase slots limit on an item by &a+{count}'
    messages:
      success:
      - '&a&l(!) &aYou have successfully increased maximum slots on item by {count}!'
  blocktrak:
    type: 'slime_ball'
    name: '&aBlockTrak Creator'
    lore:
    - '&7Track how many blocks you break with a tool'
    - '&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &aBlockTrak Creator'
    settings:
      lore-display: '&eBlockTrak Blocks Broken: &6%stats%'
  stattrak:
    type: MAGMA_CREAM
    id: 0
    custom-model-data: 0
    name: '&eStatTrak Creator'
    lore:
    - '&7Track how many kills you have with a weapon'
    - '&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &eStatTrak Creator'
    settings:
      lore-display: '&eStatTrak Kills: &6%stats%'
  mobtrak:
    type: SLIME_BALL
    id: 0
    custom-model-data: 0
    name: '&3MobTrak Creator'
    lore:
    - '&7track how many mob kills you have with a weapon'
    - '&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &3MobTrak Creator'
    settings:
      lore-display: '&3MobTrak Kills: &f%stats%'
  holywhitescroll:
    type: PAPER
    id: 0
    custom-model-data: 0
    name: '&6&lHoly White Scroll'
    lore:
    - '&eA legendary reward that can'
    - '&ebe applied to armor/weapons,'
    - '&egives a 100% chance of not losing'
    - '&ethe blessed item on death.'
    messages:
      applied:
      - '&7You successfully applied &6&lHoly White Scroll'
    settings:
      lore-display: '&e&l*&f&lHOLY&e&l* &f&lPROTECTED'
      keep-after-death: false
  orb:
    lore: '&a%max% Enchantment Slots &7(Orb [&a+%increased%&7])'
    weapon:
      material: EYE_OF_ENDER
      custom-model-data: 0
      name: '&6&lWeapon Enchantment Orb &6[&a&n%max%&6]'
      lore:
      - '&a%success%% Success Rate'
      - ''
      - '&6+%new% Enchantment slots'
      - '&6%max% Max Enchantment Slots'
      - ''
      - '&eIncreases the # of enchantment'
      - '&eslots on a weapon by %new%,'
      - '&eup to a maximum of %max%'
      - '&7Drag n'' Drop onto an item to apply.'
    armor:
      material: EYE_OF_ENDER
      custom-model-data: 0
      name: '&6&lArmor Enchantment Orb &6[&a&n%max%&6]'
      lore:
      - '&a%success%% Success Rate'
      - ''
      - '&6+%new% Enchantment slots'
      - '&6%max% Max Enchantment Slots'
      - ''
      - '&eIncreases the # of enchantment'
      - '&eslots on a piece of armor by %new%,'
      - '&eup to a maximum of %max%'
      - '&7Drag n'' Drop onto an item to apply.'
    tool:
      material: EYE_OF_ENDER
      custom-model-data: 0
      name: '&6&lTool Enchantment Orb &6[&a&n%max%&6]'
      lore:
      - '&a%success%% Success Rate'
      - ''
      - '&6+%new% Enchantment slots'
      - '&6%max% Max Enchantment Slots'
      - ''
      - '&eIncreases the # of enchantment'
      - '&eslots on a tool by %new%,'
      - '&eup to a maximum of %max%'
      - '&7Drag n'' Drop onto an item to apply.'
white-scroll:
  delete: true
  lore-display: '&f&lPROTECTED'
  item:
    type: EMPTY_MAP
    id: 0
    custom-model-data: 0
    force-glow: false
    name: '&fWhite Scroll'
    lore:
    - '&fPrevents an item from being destroyed'
    - '&fdue to a failed Enchantment Book.'
    - '&ePlace scroll on item to apply.'